export const TOGGLE_TABLE = "TOGGLE_TABLE";
export const LOAD_ANIMATED = "LOAD_ANIMATED";
export const DONT_SHOW_NOTIFICATIONS = "DONT_SHOW_NOTIFICATIONS";
export const SELECTED_COUNTRIES = "SELECTED_COUNTRIES";
